In [1]:
import os
import pandas as pd
#import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.ticker import AutoMinorLocator

In [13]:
directory = r"H:\Cruickshank\2021\troubleshooting_lidar\lidar_extract\revised_lidar_12022"
os.chdir(directory)
P01 = pd.read_csv("Cruickshnak_P01_revised.csv", encoding= 'unicode_escape')
display(P01)
list1 = list(P01)
P01 = P01[['ACO_Flight_Number','Plot_ID','cardinal', 'distance','easting','northing','depth','sd_revised_CRU_P01','sd_original_lidar_no_coreg']]

,Shape,ACO_Flight_Number,Plot_ID,SWE,Study_Area,Survey_Start_Time,cardinal,core,density,depth,...,plot_type,plug,sample_type,aspect,canopy_cover,canopy_density,canopy_height,slope,sd_revised_CRU_P01,sd_original_lidar_no_coreg
0,Point Z,1,CRU_E3S,95.276429,Cruickshank,3/10/2021 14:43,Centre,274,0.283561,336.0,...,Cardinal 10 m,0,Density,160.20250,<Null>,0,0,6.592496,0.779907,0.949951
1,Point Z,1,CRU_E7S,59.186872,Cruickshank,3/11/2021 15:15,Centre,225,0.259592,228.0,...,Cardinal 10 m,2,Density,355.04320,<Null>,0,0,8.082510,0.869995,1.230042
2,Point Z,1,CRU_N3O,163.846585,Cruickshank,3/10/2021 10:21,Centre,448,0.390111,420.0,...,Cardinal 10 m,13,Density,99.42405,<Null>,0,0,6.130295,0.919922,1.099976
3,Point Z,1,CRU_N3O,163.846585,Cruickshank,3/10/2021 10:21,Centre,448,0.390111,420.0,...,Cardinal 10 m,13,Density,99.42405,<Null>,0,0,6.130295,0.919922,1.099976
4,Point Z,1,CRU_N4S,192.71823,Cruickshank,3/10/2021 12:28,Centre,460.5,0.458853,420.0,...,Cardinal 10 m,0,Density,302.31620,<Null>,0,0,18.241920,1.089966,1.565552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Point Z,1,CRU_snowsurvey,117.651953,Cruickshank,3/9/2021 9:59,<Null>,406,0.274247,429.0,...,wx_snow_survey,2,Density,336.53810,<Null>,0,0,9.817681,1.019897,1.449951
91,Point Z,1,CRU_snowsurvey,119.095536,Cruickshank,3/9/2021 9:59,<Null>,403,0.270672,440.0,...,wx_snow_survey,2,Density,336.53810,<Null>,0,0,9.817681,1.019897,1.449951
92,Point Z,1,CRU_snowsurvey,88.780308,Cruickshank,3/9/2021 9:59,<Null>,428,0.203159,437.0,...,wx_snow_survey,9,Density,336.53810,<Null>,0,0,9.817681,1.019897,1.449951
93,Point Z,1,CRU_snowsurvey,92.894518,Cruickshank,3/9/2021 9:59,<Null>,340,0.235176,395.0,...,wx_snow_survey,8,Density,336.53810,<Null>,0,0,9.817681,1.019897,1.449951
94,Point Z,1,CRU_WX_SR50,<Null>,Cruickshank,3/9/2021 2:59,<Null>,<Null>,<Null>,430.0,...,wx_snow_survey,<Null>,Depth,89.81492,<Null>,0,0,4.950556,1.270020,1.349976

In [14]:
display(P01)
P01["sd_revised_CRU_P01"]=(P01["sd_revised_CRU_P01"]*100).round(1)
P01["sd_original_lidar_no_coreg"]=(P01["sd_original_lidar_no_coreg"]*100).round(1)
display(P01)

,ACO_Flight_Number,Plot_ID,cardinal,distance,easting,northing,depth,sd_revised_CRU_P01,sd_original_lidar_no_coreg
0,1,CRU_E3S,Centre,<Null>,329432.389,5504540.275,336.0,0.779907,0.949951
1,1,CRU_E7S,Centre,<Null>,330730.029,5503354.767,228.0,0.869995,1.230042
2,1,CRU_N3O,Centre,<Null>,328983.599,5504640.860,420.0,0.919922,1.099976
3,1,CRU_N3O,Centre,<Null>,328983.599,5504640.860,420.0,0.919922,1.099976
4,1,CRU_N4S,Centre,<Null>,328488.760,5505112.774,420.0,1.089966,1.565552
...,...,...,...,...,...,...,...,...,...
90,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,429.0,1.019897,1.449951
91,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,440.0,1.019897,1.449951
92,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,437.0,1.019897,1.449951
93,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,395.0,1.019897,1.449951
94,1,CRU_WX_SR50,<Null>,<Null>,329591.912,5504506.718,430.0,1.270020,1.349976

,ACO_Flight_Number,Plot_ID,cardinal,distance,easting,northing,depth,sd_revised_CRU_P01,sd_original_lidar_no_coreg
0,1,CRU_E3S,Centre,<Null>,329432.389,5504540.275,336.0,78.0,95.0
1,1,CRU_E7S,Centre,<Null>,330730.029,5503354.767,228.0,87.0,123.0
2,1,CRU_N3O,Centre,<Null>,328983.599,5504640.860,420.0,92.0,110.0
3,1,CRU_N3O,Centre,<Null>,328983.599,5504640.860,420.0,92.0,110.0
4,1,CRU_N4S,Centre,<Null>,328488.760,5505112.774,420.0,109.0,156.6
...,...,...,...,...,...,...,...,...,...
90,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,429.0,102.0,145.0
91,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,440.0,102.0,145.0
92,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,437.0,102.0,145.0
93,1,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,395.0,102.0,145.0
94,1,CRU_WX_SR50,<Null>,<Null>,329591.912,5504506.718,430.0,127.0,135.0

In [15]:
P01.to_csv("CRU_P01_revised.csv")

In [24]:
P02 = pd.read_csv("CRU_P02_revised.csv", encoding= 'unicode_escape')
display(P02)
list1 = list(P02)
P02 = P02[['ACO_Flight_Number','Plot_ID','cardinal', 'distance','easting','northing','depth','sd_revised_CRU_P02_no_coreg','sd_original_lidar_P02_nocoreg']]
display(P02)

,OBJECTID,Shape,ACO_Flight_Number,Plot_ID,SWE,Study_Area,Survey_Start_Time,cardinal,core,density,...,notes,plot_type,plug,aspect,canopy_cover,canopy_density,canopy_height,slope,sd_revised_CRU_P02_no_coreg,sd_original_lidar_P02_nocoreg
0,1,Point Z,2,CRU_S4F,75.788068,Cruickshank,2021-04-09T13:31:00Z,Centre,190,0.233914,...,10 cm from centre tree. Tree is dead no branches,Cardinal 10 m,0,156.78950,100,71.4,18,22.812920,-0.609985,-0.329956
1,2,Point Z,2,CRU_S2F,73.622695,Cruickshank,2021-04-09T10:52:00Z,Centre,247,0.219115,...,High side of centre pt,Cardinal 10 m,5,155.12700,100,77.3,4,38.423660,-1.180054,-0.714356
2,3,Point Z,2,CRU_S5O,95.276429,Cruickshank,2021-04-09T14:44:00Z,Centre,177,0.32188,...,<Null>,Cardinal 10 m,1,264.74940,<Null>,0,0,5.502681,0.040039,0.044189
3,4,Point Z,2,CRU_S3F,117.651953,Cruickshank,2021-04-09T12:14:00Z,Centre,325,0.302447,...,<Null>,Cardinal 10 m,3,198.70670,<Null>,100,17,16.665150,-1.050049,-1.052246
4,5,Point Z,2,CRU_N1A,20.931943,Cruickshank,2021-04-06T12:00:00Z,Centre,190,0.093865,...,<Null>,Cardinal 10 m,0,346.19790,<Null>,0,0,8.642365,-0.090088,-0.109985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,259,Point Z,2,CRU_snowsurvey,99.607175,Cruickshank,2021-04-05T05:30:00Z,<Null>,404,0.2541,...,<Null>,wx_snow_survey,11,336.53810,<Null>,0,0,9.817681,0.299927,0.299927
259,260,Point Z,2,CRU_snowsurvey,112.599416,Cruickshank,2021-04-05T05:30:00Z,<Null>,386,0.283626,...,<Null>,wx_snow_survey,0,336.53810,<Null>,0,0,9.817681,0.299927,0.299927
260,261,Point Z,2,CRU_snowsurvey,123.426282,Cruickshank,2021-04-05T05:30:00Z,<Null>,398,0.330902,...,<Null>,wx_snow_survey,4,336.53810,<Null>,0,0,9.817681,0.299927,0.299927
261,262,Point Z,2,CRU_snowpillow,95.99822,Cruickshank,2021-04-05T06:00:00Z,<Null>,422,0.254637,...,<Null>,wx_snow_survey,0,138.63850,<Null>,0,0,2.513931,-0.270020,-0.337647
262,263,Point Z,2,CRU_WX_SR50,<Null>,Cruickshank,2021-04-05T06:00:00Z,<Null>,<Null>,<Null>,...,<Null>,wx_snow_survey,<Null>,89.81492,<Null>,0,0,4.950556,0.109985,0.089966

,ACO_Flight_Number,Plot_ID,cardinal,distance,easting,northing,depth,sd_revised_CRU_P02_no_coreg,sd_original_lidar_P02_nocoreg
0,2,CRU_S4F,Centre,<Null>,328998.829,5504069.787,324,-0.609985,-0.329956
1,2,CRU_S2F,Centre,<Null>,328740.519,5504647.014,336,-1.180054,-0.714356
2,2,CRU_S5O,Centre,<Null>,329405.455,5503819.632,296,0.040039,0.044189
3,2,CRU_S3F,Centre,<Null>,328738.669,5504269.633,389,-1.050049,-1.052246
4,2,CRU_N1A,Centre,<Null>,328013.670,5504526.078,223,-0.090088,-0.109985
...,...,...,...,...,...,...,...,...,...
258,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,392,0.299927,0.299927
259,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,397,0.299927,0.299927
260,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,373,0.299927,0.299927
261,2,CRU_snowpillow,<Null>,<Null>,329589.580,5504502.042,377,-0.270020,-0.337647
262,2,CRU_WX_SR50,<Null>,<Null>,329591.912,5504506.718,408,0.109985,0.089966

In [25]:
display(P02)
P02["sd_revised_CRU_P02_no_coreg"]=(P02["sd_revised_CRU_P02_no_coreg"]*100).round(1)
P02["sd_original_lidar_P02_nocoreg"]=(P02["sd_original_lidar_P02_nocoreg"]*100).round(1)
display(P02)

,ACO_Flight_Number,Plot_ID,cardinal,distance,easting,northing,depth,sd_revised_CRU_P02_no_coreg,sd_original_lidar_P02_nocoreg
0,2,CRU_S4F,Centre,<Null>,328998.829,5504069.787,324,-0.609985,-0.329956
1,2,CRU_S2F,Centre,<Null>,328740.519,5504647.014,336,-1.180054,-0.714356
2,2,CRU_S5O,Centre,<Null>,329405.455,5503819.632,296,0.040039,0.044189
3,2,CRU_S3F,Centre,<Null>,328738.669,5504269.633,389,-1.050049,-1.052246
4,2,CRU_N1A,Centre,<Null>,328013.670,5504526.078,223,-0.090088,-0.109985
...,...,...,...,...,...,...,...,...,...
258,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,392,0.299927,0.299927
259,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,397,0.299927,0.299927
260,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,373,0.299927,0.299927
261,2,CRU_snowpillow,<Null>,<Null>,329589.580,5504502.042,377,-0.270020,-0.337647
262,2,CRU_WX_SR50,<Null>,<Null>,329591.912,5504506.718,408,0.109985,0.089966

,ACO_Flight_Number,Plot_ID,cardinal,distance,easting,northing,depth,sd_revised_CRU_P02_no_coreg,sd_original_lidar_P02_nocoreg
0,2,CRU_S4F,Centre,<Null>,328998.829,5504069.787,324,-61.0,-33.0
1,2,CRU_S2F,Centre,<Null>,328740.519,5504647.014,336,-118.0,-71.4
2,2,CRU_S5O,Centre,<Null>,329405.455,5503819.632,296,4.0,4.4
3,2,CRU_S3F,Centre,<Null>,328738.669,5504269.633,389,-105.0,-105.2
4,2,CRU_N1A,Centre,<Null>,328013.670,5504526.078,223,-9.0,-11.0
...,...,...,...,...,...,...,...,...,...
258,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,392,30.0,30.0
259,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,397,30.0,30.0
260,2,CRU_snowsurvey,<Null>,<Null>,329584.780,5504523.844,373,30.0,30.0
261,2,CRU_snowpillow,<Null>,<Null>,329589.580,5504502.042,377,-27.0,-33.8
262,2,CRU_WX_SR50,<Null>,<Null>,329591.912,5504506.718,408,11.0,9.0

In [28]:
P02.to_csv("CRU_P02_revised_1.csv")